export const ui = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MCP Registry</title>
<style>
:root{--ink:#101827;--muted:#697386;--line:#e6e7eb;--paper:#fffdfa;--soft:#fff7ed;--orange:#ff7a18;--orange-dark:#d94f05;--green:#178f55;--shadow:0 18px 50px rgba(23,18,10,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}button,input,select{font:inherit}button,a{transition:.18s ease}button{cursor:pointer}code,pre{font-family:SFMono-Regular,Consolas,monospace}
.header{position:sticky;top:0;z-index:10;background:#fffdfaeF;backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.header-inner{height:82px;max-width:1420px;margin:auto;padding:0 42px;display:flex;align-items:center;gap:42px}.brand{display:flex;align-items:center;gap:12px;margin-right:auto;font-size:23px;font-weight:800;letter-spacing:-.7px}.brand-mark{width:40px;height:40px;display:grid;place-items:center;border:2px solid var(--ink);border-radius:12px 12px 16px 10px;color:var(--orange);font-size:21px;transform:rotate(-3deg)}.brand em{font-style:normal;color:var(--orange)}
nav{display:flex;align-items:center;gap:8px}nav button{border:0;background:transparent;color:#4d5667;padding:12px 16px;border-radius:11px;font-weight:650}nav button:hover,nav button.active{color:var(--orange-dark);background:var(--soft)}.publish-nav{background:var(--orange)!important;color:white!important;padding-inline:21px!important;box-shadow:0 8px 20px #ff7a1835}
main{min-height:calc(100vh - 82px)}.view{display:none}.view.active{display:block}.container{max-width:1420px;margin:auto;padding:54px 42px 90px}
.hero{position:relative;overflow:hidden;text-align:center;padding:92px 32px 72px;background:radial-gradient(circle at 82% 18%,#fff1df 0,transparent 29%),radial-gradient(circle at 15% 70%,#fff8ed 0,transparent 30%)}.hero:after{content:"";position:absolute;inset:0;pointer-events:none;background-image:radial-gradient(#f1b57a55 1px,transparent 1px);background-size:26px 26px;mask-image:linear-gradient(to bottom,transparent,#000 35%,transparent)}.hero-content{position:relative;z-index:1;max-width:1120px;margin:auto}.eyebrow{display:inline-flex;align-items:center;gap:10px;padding:11px 20px;border:1px solid #ffc98f;border-radius:999px;background:#fffaf3;color:#8a3417;font-weight:800;letter-spacing:.06em;text-transform:uppercase;box-shadow:0 3px 0 #ffdfbd}.eyebrow span{color:var(--orange);font-size:20px}.hero h1{margin:42px 0 22px;font-family:inherit;font-size:clamp(54px,6.8vw,104px);line-height:.98;letter-spacing:-.065em;font-weight:700}.hero h1 strong{color:var(--orange);font-weight:inherit}.hero-copy{max-width:780px;margin:0 auto;color:#566071;font-size:22px}.hero-copy b{color:var(--ink)}
.search-shell{max-width:980px;margin:54px auto 0;display:flex;align-items:center;gap:16px;padding:14px 15px 14px 25px;background:white;border:2px solid #e3e5e9;border-radius:24px;box-shadow:0 16px 42px #33201013}.search-icon{font-size:29px;color:#9aa2b1}.search-shell input{min-width:0;flex:1;border:0;outline:0;font-size:20px;color:var(--ink);background:transparent}.search-shell input::placeholder{color:#9ca3b2}.search-submit{width:58px;height:58px;border:0;border-radius:17px;background:var(--orange);color:white;font-size:27px;box-shadow:0 10px 24px #ff7a1840}.search-submit:hover{background:var(--orange-dark);transform:translateY(-2px)}.proof{display:flex;justify-content:center;gap:40px;flex-wrap:wrap;margin-top:32px;color:#687183;font-weight:600}.proof span:before{content:"✓";display:inline-grid;place-items:center;width:22px;height:22px;margin-right:8px;border-radius:50%;background:#edf9f1;color:var(--green);font-size:12px}
.market{max-width:1420px;margin:auto;padding:36px 42px 100px}.market-head{display:flex;align-items:end;gap:24px;margin-bottom:24px}.market-head h2{font-family:inherit;font-size:38px;margin:0;letter-spacing:-.025em}.market-head p{margin:0 0 7px;color:var(--muted)}.filters{display:flex;gap:12px;margin-left:auto}.filters select{border:1px solid #dfe1e6;background:white;padding:11px 38px 11px 14px;border-radius:12px;color:#4e5665}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.card{position:relative;background:white;border:1px solid var(--line);border-radius:20px;padding:25px;box-shadow:0 3px 0 #eceef1}.package-card{min-height:255px;display:flex;flex-direction:column}.package-card:hover{transform:translateY(-4px);border-color:#ffc685;box-shadow:var(--shadow)}.card-top,.row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.grow{flex:1}.package-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:15px;background:var(--soft);border:1px solid #ffd8ad;color:var(--orange-dark);font:800 18px Georgia,serif}.card h3{margin:0;font-size:20px;line-height:1.25}.package-name{margin:13px 0 0;color:#89909e;font-size:12px}.description{color:#606979;margin:20px 0;flex:1}.tags{display:flex;gap:7px;flex-wrap:wrap}.tag{display:inline-flex;align-items:center;padding:4px 9px;border-radius:999px;background:#fff4e7;color:#a4420c;border:1px solid #ffd3a1;font-size:12px;font-weight:700}.tag.neutral{background:#f5f6f8;color:#555f70;border-color:#e5e7eb}.tag.green{background:#edf9f2;color:#157a49;border-color:#b8ebcf}.actions{display:flex;gap:9px;margin-top:20px}.primary,.secondary{border-radius:11px;padding:10px 14px;font-weight:750}.primary{border:1px solid var(--orange);background:var(--orange);color:white}.primary:hover{background:var(--orange-dark);border-color:var(--orange-dark)}.secondary{border:1px solid #dfe1e5;background:white;color:#303949}.secondary:hover{border-color:var(--orange);color:var(--orange-dark)}
.page-heading{display:flex;align-items:end;gap:20px;margin-bottom:30px}.page-heading h1{font-family:inherit;font-size:48px;line-height:1;font-weight:700;letter-spacing:-.04em;margin:0}.page-heading p{color:var(--muted);margin:0 0 3px}.online-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.route{white-space:pre-wrap;word-break:break-all;background:#171d29;color:#ffd7b1;padding:16px;border-radius:13px;font-size:12px}.npm-source{color:#858d9b;font-size:13px}.status-dot:before{content:"";display:inline-block;width:8px;height:8px;border-radius:50%;background:#a2a8b2;margin-right:7px}.status-dot.active:before{background:#1fbd70;box-shadow:0 0 0 4px #e8faef}.drop{border:2px dashed #ffc37d;text-align:center;padding:42px;border-radius:17px;background:#fffaf4}.publish-grid,.admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.admin-grid{grid-template-columns:repeat(3,minmax(0,1fr))}pre{overflow:auto;background:#f6f6f7;padding:16px;border-radius:12px}.muted{color:var(--muted)}
.drawer{position:fixed;z-index:30;right:-760px;top:0;width:min(760px,100%);height:100vh;background:white;border-left:1px solid var(--line);padding:32px;overflow:auto;transition:.25s;box-shadow:-18px 0 60px #0002}.drawer.open{right:0}.overlay{display:none;position:fixed;inset:0;background:#13172280;z-index:20;backdrop-filter:blur(3px)}.overlay.open{display:block}.desc{display:grid;grid-template-columns:145px 1fr;border:1px solid var(--line);border-bottom:0;margin-top:18px}.desc>*{padding:11px;border-bottom:1px solid var(--line)}.desc b{background:#faf9f7}.readme{line-height:1.75;overflow-wrap:anywhere}.readme h1,.readme h2,.readme h3{color:var(--ink);line-height:1.25;margin:28px 0 12px}.readme h1{font-size:28px}.readme h2{font-family:inherit;font-size:22px;border-bottom:1px solid var(--line);padding-bottom:9px}.readme h3{font-size:18px}.readme p,.readme ul,.readme ol{margin:12px 0}.readme a{color:var(--orange-dark);text-decoration:underline;text-underline-offset:3px}.readme pre{padding:16px;border:1px solid var(--line);background:#f7f7f8}.readme code{font-size:.9em}.readme img{max-width:100%;height:auto;border-radius:10px}.readme blockquote{margin:16px 0;padding:2px 16px;border-left:4px solid var(--orange);color:var(--muted)}.readme table{width:100%;border-collapse:collapse;margin:18px 0}.readme th,.readme td{border:1px solid var(--line);padding:9px;text-align:left}.readme th{background:var(--soft)}.empty{grid-column:1/-1;text-align:center;padding:54px;color:var(--muted)}
@keyframes rise{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}.hero-content>*{animation:rise .55s both}.hero h1{animation-delay:.08s}.hero-copy{animation-delay:.16s}.search-shell{animation-delay:.24s}.proof{animation-delay:.32s}
@media(max-width:950px){.header-inner{padding:0 20px}.brand span{display:none}nav{gap:2px}nav button{padding:10px}.grid,.admin-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.market-head{align-items:start;flex-direction:column}.filters{margin-left:0}}@media(max-width:650px){.header-inner{height:auto;min-height:72px;flex-wrap:wrap;padding-block:12px}.brand{margin-right:0}.header nav{order:2;width:100%;overflow:auto}.publish-nav{display:none}.hero{padding:68px 18px 48px}.hero h1{font-size:50px}.hero-copy{font-size:18px}.search-shell{margin-top:35px}.proof{gap:14px}.market,.container{padding:28px 18px 70px}.grid,.online-grid,.publish-grid,.admin-grid{grid-template-columns:1fr}.filters{width:100%;overflow:auto}.page-heading{align-items:start;flex-direction:column}.page-heading h1{font-size:39px}}
</style>
</head>
<body>
<header class="header"><div class="header-inner"><div class="brand"><div class="brand-mark">⌁</div><span><em>MCP</em> Registry</span></div><nav><button data-view="list" class="active">Explore</button><button data-view="online">Online MCP</button><button data-view="admin">Insights</button><button data-view="publish" class="publish-nav">Publish package</button></nav></div></header>
<main>
<section id="list" class="view active">
  <div class="hero"><div class="hero-content"><div class="eyebrow"><span>✦</span><b id="packageCount">MCP PACKAGES READY TO RUN</b></div><h1>Find Your Next<br><strong>AI Capability</strong></h1><p class="hero-copy">Discover installable MCP servers from your NPM sources. <b>Deploy a verified route in seconds.</b></p><form class="search-shell" onsubmit="event.preventDefault();loadPackages()"><span class="search-icon">⌕</span><input id="search" aria-label="Search MCP packages" placeholder="Search MCP servers by name or capability…"><button class="search-submit" aria-label="Search">↵</button></form><div class="proof"><span>NPM authoritative</span><span>Live projection cache</span><span>Ready-to-copy routes</span></div></div></div>
  <div class="market"><div class="market-head"><div><h2>Explore MCP servers</h2><p>Server packages discovered from the <code>mcp-plugin</code> keyword.</p></div><div class="filters"><select id="typeFilter" onchange="renderPackages()"><option value="all">All runtimes</option><option value="serverless">HTTP Server</option></select><select id="sortFilter" onchange="renderPackages()"><option value="name">Sort: Name</option><option value="newest">Sort: Newest</option></select></div></div><div id="packages" class="grid"></div></div>
</section>
<section id="online" class="view"><div class="container"><div class="page-heading"><div class="grow"><h1>Online MCP</h1><p>Healthy Worker deployments mounted behind stable Registry routes.</p></div><button class="primary" onclick="loadDeployments()">Refresh routes</button></div><div id="deployments" class="online-grid"></div></div></section>
<section id="publish" class="view"><div class="container"><div class="page-heading"><div><h1>Publish</h1><p>NPM remains authoritative; Registry creates no second package record.</p></div></div><div class="publish-grid"><div class="card"><h3>Inspect a package folder</h3><div class="drop"><input id="folder" type="file" webkitdirectory multiple><p>Files remain in this browser. Manifests are validated locally.</p></div><div id="folderResult"></div></div><div class="card"><h3>Publish with npm</h3><p class="muted">Authenticate, inspect the tarball, then publish.</p><pre>npm adduser --registry http://localhost:4873
npm pack --dry-run
npm publish --registry http://localhost:4873</pre><p><b>Registry recognition contract</b></p><p class="muted">Publish this metadata in the package root <code>package.json</code>. Put <code>README.md</code> beside it; npm includes the README in package metadata.</p><pre>{
  "name": "@your-org/example-mcp",
  "version": "1.0.0",
  "description": "What this MCP server does",
  "keywords": ["mcp-plugin"],
  "files": ["dist", "README.md"],
  "mcpp": {
    "display": {
      "name": "Example MCP",
      "description": "A short market description"
    },
    "servers": {
      "default": {
        "title": "Example MCP Server",
        "runtime": "serverless",
        "entry": "./dist/server.js",
        "endpointPath": "/mcp"
      }
    }
  }
}</pre><p class="muted">The entry module must export <code>fetch(Request)</code> or <code>default.fetch(Request)</code>. The Registry discovers <code>mcp-plugin</code>, then validates <code>mcpp.servers</code>; README alone is not enough.</p></div></div></div></section>
<section id="admin" class="view"><div class="container"><div class="page-heading"><div><h1>Insights</h1><p>Operational boundaries for this Registry instance.</p></div></div><div class="admin-grid"><div class="card"><span class="tag">SOURCE</span><h3>NPM projection</h3><p><code>default</code> → <code>http://npm:4873</code></p><p class="muted">Package metadata and dist-tags remain authoritative.</p></div><div class="card"><span class="tag">RUNTIME</span><h3>Worker lifecycle</h3><p>Resolve → install → load → probe → activate.</p><p class="muted">Bun Worker is a prototype boundary, not a security sandbox.</p></div><div class="card"><span class="tag">ROUTING</span><h3>Mono Server</h3><p>Registry forwards each declared endpoint path to its active Worker.</p></div></div></div></section>
</main>
<div id="overlay" class="overlay" onclick="closeDetail()"></div><aside id="detail" class="drawer"><div class="row"><h2 class="grow">Package details</h2><button class="secondary" onclick="closeDetail()">Close</button></div><div id="detailBody"></div></aside>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let packageCache=[];window.deploymentCache=[];
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active');if(b.dataset.view==='online')loadDeployments();window.scrollTo({top:0})});
async function loadPackages(){packages.innerHTML='<div class="card empty">Loading the NPM projection…</div>';const r=await fetch('/api/packages?q='+encodeURIComponent(search.value));const data=await r.json();packageCache=Array.isArray(data)?data:[];packageCount.textContent=packageCache.length+' MCP PACKAGES READY TO RUN';renderPackages()}
function renderPackages(){let items=[...packageCache];if(sortFilter.value==='name')items.sort((a,b)=>a.name.localeCompare(b.name));else items.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));packages.innerHTML=items.map(p=>{const i=packageCache.indexOf(p);const short=p.name.split('/').pop();return '<article class="card package-card"><div class="card-top"><div class="package-icon">'+esc(short.slice(0,2).toUpperCase())+'</div><div class="grow"><h3>'+esc(short.replace(/-mcp$/,''))+'</h3><p class="package-name">'+esc(p.name)+'@'+esc(p.version)+'</p></div><span class="tag">HTTP</span></div><p class="description">'+esc(p.description||'No package description provided.')+'</p><div class="tags">'+(p.keywords||[]).slice(0,3).map(k=>'<span class="tag neutral">'+esc(k)+'</span>').join('')+'</div><div class="actions"><button class="secondary grow" onclick="showPackage('+i+')">View details</button><button class="primary" onclick="deployPackage('+i+',this)">Deploy</button></div></article>'}).join('')||'<div class="card empty"><h3>No MCP packages found</h3><p>Publish a package with the <code>mcp-plugin</code> keyword or try another search.</p></div>'}
async function showPackage(index){const summary=packageCache[index];detailBody.innerHTML='<p class="muted">Loading package metadata…</p>';openDetail();const r=await fetch('/api/packages/'+encodeURIComponent(summary.name));const p=await r.json();const servers=p.mcpp&&p.mcpp.servers?p.mcpp.servers:{};const display=p.mcpp&&p.mcpp.display?p.mcpp.display:{};const rows=Object.entries(servers).map(([id,s])=>'<div class="desc"><b>Server</b><span>'+esc(s.title||id)+'</span><b>Transport</b><span><span class="tag">'+esc(s.runtime==='serverless'?'HTTP Server':'stdio')+'</span></span><b>Runtime</b><span>'+esc(s.runtime||'client-local')+'</span><b>Endpoint</b><span><code>'+esc(s.endpointPath||'/mcp')+'</code></span></div>').join('');detailBody.innerHTML='<h2>'+esc(display.name||p.name)+'</h2><p>'+esc(display.description||p.description||'')+'</p><p class="muted">NPM package <code>'+esc(p.name)+'@'+esc(p.version)+'</code></p>'+rows+'<div class="readme"><h2>README</h2>'+(p.readmeHtml?p.readmeHtml:'<p class="muted">No README published.</p>')+'</div>'}
function openDetail(){overlay.classList.add('open');detail.classList.add('open')}function closeDetail(){overlay.classList.remove('open');detail.classList.remove('open')}
async function deployPackage(index,button){const item=packageCache[index];if(!item)return;const adminToken=prompt('Admin token required to deploy');if(!adminToken)return;const original=button.textContent;button.disabled=true;button.textContent='Queuing…';try{const r=await fetch('/api/deployments',{method:'POST',headers:{'content-type':'application/json','x-admin-token':adminToken},body:JSON.stringify({packageName:item.name,distTag:'latest',serverId:'default',sourceId:'default'})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Deployment failed');button.textContent='Queued';setTimeout(()=>document.querySelector('[data-view="online"]').click(),350)}catch(error){alert(error.message||'Deployment failed');button.disabled=false;button.textContent=original}}
async function loadDeployments(){deployments.innerHTML='<div class="card empty">Loading active routes…</div>';const r=await fetch('/api/deployments');const data=await r.json();window.deploymentCache=Array.isArray(data)?data:[];deployments.innerHTML=window.deploymentCache.map((d,i)=>'<article class="card"><div class="row"><div class="grow"><h3>'+esc(d.displayName||d.packageName)+'</h3><p class="npm-source">'+esc(d.packageName)+'@'+esc(d.version||d.distTag)+' · '+esc(d.serverTitle||d.serverId)+'</p></div><span class="tag green status-dot '+esc(d.status)+'">'+esc(d.status)+'</span></div><p class="description">'+esc(d.description||'Hosted MCP server deployment.')+'</p>'+(d.status==='active'?'<p><b>MCP Route</b></p><pre class="route">'+esc(d.route)+'</pre><div class="actions"><button class="secondary grow" onclick="showDeployment('+i+')">View details</button><button class="primary" onclick="copyConfig('+i+',this)">Copy MCP JSON</button></div>':'')+'</article>').join('')||'<div class="card empty"><h3>No online deployments</h3><p>Deploy a package from Explore to create its first MCP Route.</p></div>'}
function showDeployment(index){const d=window.deploymentCache[index];if(!d)return;const config=JSON.stringify(d.mcpJson,null,2);detailBody.innerHTML='<span class="eyebrow">ONLINE MCP</span><h2>'+esc(d.displayName||d.packageName)+'</h2><p>'+esc(d.description||'Hosted MCP server deployment.')+'</p><div class="desc"><b>Status</b><span><span class="tag green status-dot '+esc(d.status)+'">'+esc(d.status)+'</span></span><b>Server</b><span>'+esc(d.serverTitle||d.serverId)+'</span><b>NPM source</b><span><code>'+esc(d.packageName)+'@'+esc(d.version||d.distTag)+'</code></span><b>Transport</b><span>Streamable HTTP</span></div><div class="readme"><h2>Connect to this MCP</h2><p>Add the configuration below to an MCP Client. The endpoint is a protocol route, not a browser page.</p><p><b>MCP endpoint</b></p><pre class="route">'+esc(d.route)+'</pre><p><b>MCP JSON</b></p><pre>'+esc(config)+'</pre><div class="actions"><button class="primary" onclick="copyConfig('+index+',this)">Copy MCP JSON</button><button class="secondary" onclick="copyRoute('+index+',this)">Copy endpoint</button></div></div>';openDetail()}
async function copyText(value,button){try{await navigator.clipboard.writeText(value);const previous=button&&button.textContent;if(button){button.textContent='Copied';setTimeout(()=>button.textContent=previous,1200)}}catch{alert('Clipboard permission denied')} }
async function copyConfig(index,button){const item=window.deploymentCache[index];if(item)await copyText(JSON.stringify(item.mcpJson,null,2),button,'MCP JSON')}
async function copyRoute(index,button){const item=window.deploymentCache[index];if(item)await copyText(item.route,button,'endpoint')}
folder.onchange=async()=>{const files=[...folder.files];const relative=files.map(f=>f.webkitRelativePath.split('/').slice(1).join('/'));const packageFile=files.find(f=>/(^|\\/)package.json$/.test(f.webkitRelativePath));let pkg=null,error='';try{pkg=packageFile?JSON.parse(await packageFile.text()):null}catch{error='Invalid package.json'}const servers=pkg&&pkg.mcpp&&pkg.mcpp.servers;const validServers=!!servers&&Object.values(servers).every(s=>s&&s.runtime==='serverless'&&typeof s.entry==='string'&&typeof s.endpointPath==='string');const checks=[['package.json',!!pkg],['mcp-plugin keyword',!!pkg&&Array.isArray(pkg.keywords)&&pkg.keywords.includes('mcp-plugin')],['valid mcpp.servers',validServers],['README.md',relative.some(n=>/^readme.md$/i.test(n))]];folderResult.innerHTML='<h4>'+esc(pkg&&pkg.name||'Package folder')+'</h4>'+(error?'<p style="color:#c43d18">'+error+'</p>':'')+checks.map(([n,ok])=>'<p>'+(ok?'✓':'○')+' '+esc(n)+'</p>').join('')+'<p class="muted">'+files.length+' files inspected locally.</p>'};
loadPackages();
</script>
</body></html>`;
